version: '3'
services:
    ui:
        image: stephar/geospatial-data-visualisation-ui:latest
        volumes:
            -  static-ui-content:/build
    api:
        image: stephar/geospatial-data-visualisation-api:latest
        networks:
            - web_nw
    # tileserver:
    #     image: urbica/martin
    #     ports:
    #         - "${TILE_PORT1}:${TILE_PORT2}"
    #     env_file: .env
    proxy:
        build:
            context: proxy
            dockerfile: Dockerfile
        volumes:
            -  static-ui-content:/ui
        depends_on:
            - ui
            - api
        ports:
            - "8000:8000"
        networks:
            - web_nw
    postgres:
        build:
            context: ./postgres
            args:
                - POSTGRES_DB=${POSTGRES_DB}
                - POSTGRES_USER=${POSTGRES_USER}
        ports:
            - "${DB_PORT1}:${DB_PORT2}"
        env_file: .env
networks:
    web_nw:
        driver: bridge
volumes:
    static-ui-content: