version: '3'
services:
    ui:
        image: stephar/geospatial-data-visualisation-ui:latest
        volumes:
            -  static-ui-content:/build
    api:
        image: stephar/geospatial-data-visualisation-api:latest
        links:
            - postgres
        ports:
            - "${API_PORT}"
        environment:
            - DB_HOST_PORT=postgres:${DB_PORT2}
            - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/
        env_file: .env
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - web_nw
    proxy:
        build:
            context: proxy
            dockerfile: Dockerfile
        volumes:
            -  static-ui-content:/ui
        depends_on:
            - ui
            - api
        ports:
            - "${PROXY_PORT}:${PROXY_PORT}"
        depends_on:
            - api
        links:
            - api
        networks:
            - web_nw
    postgres:
        build:
            context: ./postgres
            args:
                - POSTGRES_DB=${POSTGRES_DB}
                - POSTGRES_USER=${POSTGRES_USER}
        networks:
            - web_nw
        ports:
            - "${DB_PORT1}:${DB_PORT2}"
        env_file: .env
        volumes:
            - dbData:/var/lib/postgresql/data
networks:
    web_nw:
        driver: "bridge"
volumes:
    static-ui-content:
        labels:
            persistent: 'false'
    dbData:
        labels:
            persistent: 'true'
