version: '3'
services:
    ui:
        image: stephar/geospatial-data-visualisation-ui:latest
        volumes:
            -  static-ui-content:/build
    api:
        image: stephar/geospatial-data-visualisation-api:latest
        networks:
            - web_nw
        ports:
            - "5000"
        environment:
            - DB_HOST_PORT="postgres:${DB_PORT2}"
            - DB_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432"
        env_file: .env
    # tileserver:
    #     image: urbica/martin
    #     ports:
    #         - "${TILE_PORT1}:${TILE_PORT2}"
    #     env_file: .env
    proxy:
        build:
            context: proxy
            dockerfile: Dockerfile
        volumes:
            -  static-ui-content:/ui
        depends_on:
            - ui
            - api
        ports:
            - "8000:8000"
        networks:
            - web_nw
    postgres:
        build:
            context: ./postgres
            args:
                - POSTGRES_DB=${POSTGRES_DB}
                - POSTGRES_USER=${POSTGRES_USER}
        networks:
            - web_nw
        ports:
            - "${DB_PORT1}:${DB_PORT2}"
        env_file: .env
        volumes:
            - dbData:/var/lib/postgresql/data
networks:
    web_nw:
        driver: bridge
volumes:
    static-ui-content:
        labels:
            persistent: 'false'
    dbData:
        labels:
            persistent: 'true'
